name: Python CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le depot
      uses: actions/checkout@v3

    - name: Installer Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Lancer les tests unitaires
      run: python -m unittest discover